
package services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BadBinaryAttachmentException", targetNamespace = "http://services/")
public class BadBinaryAttachmentException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PersonServiceBinaryAttachmentFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BadBinaryAttachmentException(String message, PersonServiceBinaryAttachmentFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BadBinaryAttachmentException(String message, PersonServiceBinaryAttachmentFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: services.PersonServiceBinaryAttachmentFault
     */
    public PersonServiceBinaryAttachmentFault getFaultInfo() {
        return faultInfo;
    }

}
